archPackagesUpdate option --ignore-wrong-db-signature neu

diff --git a/archPackagesUpdate b/archPackagesUpdate
--- a/archPackagesUpdate
+++ b/archPackagesUpdate
@@ -14,6 +14,7 @@ upload=true
 updateMe=true
 abortOnMakepkgError=true
 cleanUnsigned=false
+checkDbSig='-v'
 
 # print help screen
 usage()
@@ -22,19 +23,20 @@ usage()
   >&2 echo 'Skript zum Updaten der selbsterstellten Archlinux-Pakete'
   >&2 echo ''
   >&2 echo 'Verwendung:'
-  >&2 echo '  '"$0"' [ -f|--force ] [ --no-upload ] [ --no-selfUpdate ] [ --no-abortOnMakepkgError ] [ -c|--cleanUnsigned ]'
-  >&2 echo '    -f|--force:                rebuild packages even if they look up to date'
-  >&2 echo '    --no-upload:               do not upload built packages from rechenknecht to jeti100'
-  >&2 echo '    --no-selfUpdate:           do not update this script from git'
-  >&2 echo '    --no-abortOnMakepkgError:  do not abort when makepkg returns non-zero'
-  >&2 echo '    -c|--cleanUnsigned:        remove unsigned Packages first'
+  >&2 echo '  '"$0"' [ -f|--force ] [ --ignore-wrong-db-signature ] [ --no-upload ] [ --no-selfUpdate ] [ --no-abortOnMakepkgError ] [ -c|--cleanUnsigned ]'
+  >&2 echo '    -f|--force:                   rebuild packages even if they look up to date'
+  >&2 echo '    --ignore-wrong-db-signature:  do not verify old database signature'
+  >&2 echo '    --no-upload:                  do not upload built packages from rechenknecht to jeti100'
+  >&2 echo '    --no-selfUpdate:              do not update this script from git'
+  >&2 echo '    --no-abortOnMakepkgError:     do not abort when makepkg returns non-zero'
+  >&2 echo '    -c|--cleanUnsigned:           remove unsigned Packages first'
   >&2 echo ''
   rm -rf "${tmpDir}"
   exit 1
 }
 
 echo 'parse arguments ...'
-eval set -- "$(getopt -o fc --long force,no-upload,no-selfUpdate,no-abortOnMakepkgError,cleanUnsigned -n "$(basename "$0")" -- "$@" || echo "usage")"
+eval set -- "$(getopt -o fc --long force,ignore-wrong-db-signature,no-upload,no-selfUpdate,no-abortOnMakepkgError,cleanUnsigned -n "$(basename "$0")" -- "$@" || echo "usage")"
 args=("$@")
 
 while true
@@ -53,6 +55,11 @@ do
     --no-upload)
       echo '"no-upload" erkannt'
       upload=false
+      shift
+    ;;
+    --ignore-wrong-db-signature)
+      echo '"ignore-wrong-db-signature" erkannt'
+      checkDbSig=''
       shift
     ;;
     --no-selfUpdate)
@@ -109,7 +116,7 @@ then
   ssh paule@127.0.0.1 '
     rmPaket() {
       [ "$(basename "$(pwd)")" == "any" ] || \
-        repo-remove -v -s -k 0x20194BA1 archlinuxewe.db.tar.gz "${1%-*-*-*.pkg.tar.xz}"
+        repo-remove '${checkDbSig}' -s -k 0x20194BA1 archlinuxewe.db.tar.gz "${1%-*-*-*.pkg.tar.xz}"
       rm "$1"
       [ -e "$1.sig" ] && rm "$1.sig"
     }
@@ -307,7 +314,7 @@ then
 
           rmPaket() {
             [ "$(basename "$(pwd)")" == "any" ] && return
-            repo-remove -v -s -k 0x20194BA1 archlinuxewe.db.tar.gz "${1%-*-*-*.pkg.tar.xz}"
+            repo-remove '${checkDbSig}' -s -k 0x20194BA1 archlinuxewe.db.tar.gz "${1%-*-*-*.pkg.tar.xz}"
             rm "$1"
             [ -e "$1.sig" ] && rm "$1.sig"
           }
@@ -320,7 +327,7 @@ then
               [ "${alt}" == "${neu}" ] && continue
               rmPaket "${alt}"
             done
-            repo-add -v -s -k 0x20194BA1 archlinuxewe.db.tar.gz "${neu}"
+            repo-add '${checkDbSig}' -s -k 0x20194BA1 archlinuxewe.db.tar.gz "${neu}"
           }
 
           cd '${pkgDir}/${arch}/'
